# Generated by Django 4.2.5 on 2024-02-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='user_avatar/'),
        ),
    ]
