# Generated by Django 4.2.5 on 2024-03-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userdashboard_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='useravatars/'),
        ),
    ]
