# Generated by Django 4.2.5 on 2024-03-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='ascents',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
