# Generated by Django 4.2.5 on 2024-02-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
