# Generated by Django 4.2.5 on 2024-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_league_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
