# Generated by Django 4.2.5 on 2024-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_remove_league_teams_league_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='number_of_teams',
            field=models.IntegerField(default=0),
        ),
    ]
