# Generated by Django 4.2.5 on 2024-02-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_league_number_of_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='league_photos/'),
        ),
    ]
