# Generated by Django 4.2.5 on 2024-03-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_league_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='picture',
            new_name='pictue',
        ),
    ]
