# Generated by Django 4.2.5 on 2024-03-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_rename_picture_league_pictue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='pictue',
            field=models.FileField(blank=True, null=True, upload_to='leaguephotos/'),
        ),
    ]
