# Generated by Django 4.2.5 on 2024-03-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_league_pictue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='pictue',
            new_name='picture',
        ),
    ]
