# Generated by Django 4.2.5 on 2024-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
