# Generated by Django 4.2.5 on 2024-02-21 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boulder', '0001_initial'),
        ('send', '0002_send_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='boulder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boulder', to='boulder.boulder'),
        ),
        migrations.AlterField(
            model_name='send',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to=settings.AUTH_USER_MODEL),
        ),
    ]
