# Generated by Django 4.2.5 on 2024-02-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_remove_league_teams_league_participants_and_more'),
        ('team', '0004_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='league.league'),
            preserve_default=False,
        ),
    ]
