# Generated by Django 4.2.5 on 2024-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
