# Generated by Django 4.2.5 on 2024-03-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_team_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_picture',
            field=models.FileField(blank=True, null=True, upload_to='teamphotos/'),
        ),
    ]
